services:
  - type: web
    name: woolcraft
    runtime: docker
    repo: https://github.com/shubhyagami/eCommerce
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
